name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Save test private key file from secrets
      run: envsubst < private.key.envsubst.txt > private.key
    - name: Save test cert file from secrets
      run: envsubst < server.crt.envsubst.txt > server.crt
    - name: Run tests
      run: cargo test --verbose
