name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:4.1.0
        ports:
          - 9044:9042
        options: --health-cmd 'cqlsh -e "USE system"' --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Save test private key file from secrets
      run: envsubst < private.key.envsubst.txt > private.key
      env:
        TEST_PRIVATE_SERVER_KEY: ${{ secrets.TEST_PRIVATE_SERVER_KEY }}
    - name: Save test cert file from secrets
      run: envsubst < server.crt.envsubst.txt > server.crt
      env:
        TEST_SERVER_CERT: ${{ secrets.TEST_SERVER_CERT }}
    - name: Run tests
      run: cargo test -- --nocapture
